apiversion: app/v1
kind: Deployment
metadata:
  name: myapp-deployment
specs:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp-pod
      label:
        app: myapp
    specs:
      containers:
        - name: myapp-container
          image: nginx
          ports:
            - containerPort: 80